import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View, type StyleProp, type ViewStyle } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useApp } from '@/context/AppContext'; import { colorsFor, fonts } from '@/theme/theme';
function BrandFooter() { const { dark } = useApp(); const C = colorsFor(dark); return <View style={styles.footer}><Text style={[styles.footerBrand, { color: C.subtext }]}>Netora</Text><Text style={[styles.footerTag, { color: C.subtext }]}>Network utility for Android</Text></View>; }
export function Screen({ children, scroll = true }: { children: React.ReactNode; scroll?: boolean }) { const { dark } = useApp(); const C = colorsFor(dark); const insets = useSafeAreaInsets(); const top = insets.top + 10; const bottom = insets.bottom + 28; const body = <View style={styles.screen}>{children}<BrandFooter /></View>; if (!scroll) return <View style={[styles.screen, { backgroundColor: C.background, paddingTop: top, paddingBottom: bottom }]}>{body}</View>; return <ScrollView style={[styles.scroll, { backgroundColor: C.background }]} contentContainerStyle={{ flexGrow: 1, paddingTop: top, paddingBottom: bottom }} showsVerticalScrollIndicator={false}>{body}</ScrollView>; }
export function Header({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) { const { dark } = useApp(); const C = colorsFor(dark); return <View style={styles.header}><View style={{ flex: 1 }}><Text style={[styles.title, { color: C.text }]}>{title}</Text>{subtitle && <Text style={[styles.subtitle, { color: C.subtext }]}>{subtitle}</Text>}</View>{action}</View>; }
export function Card({ children, style }: { children: React.ReactNode; style?: StyleProp<ViewStyle> }) { const { dark } = useApp(); const C = colorsFor(dark); return <View style={[styles.card, { backgroundColor: C.surface, borderColor: C.line }, style]}>{children}</View>; }
export function Label({ children }: { children: React.ReactNode }) { const { dark } = useApp(); return <Text style={[styles.label, { color: colorsFor(dark).subtext }]}>{children}</Text>; }
export function Metric({ label, value, unit }: { label: string; value: string | number; unit?: string }) { const { dark } = useApp(); const C = colorsFor(dark); return <View style={styles.metric}><Label>{label}</Label><Text style={[styles.metricValue, { color: C.text }]}>{value} <Text style={[styles.metricUnit, { color: C.subtext }]}>{unit}</Text></Text></View>; }
export function Row({ icon, label, value, onPress }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string; onPress?: () => void }) { const { dark } = useApp(); const C = colorsFor(dark); return <Pressable onPress={onPress} style={styles.row}><Ionicons name={icon} size={19} color={C.accent} /><Text style={[styles.rowLabel, { color: C.subtext }]}>{label}</Text><Text numberOfLines={1} style={[styles.rowValue, { color: C.text }]}>{value}</Text>{onPress && <Ionicons name="chevron-forward" size={17} color={C.subtext} />}</Pressable>; }
export function Pill({ children, tone = 'accent' }: { children: React.ReactNode; tone?: 'accent' | 'muted' }) { const { dark } = useApp(); const C = colorsFor(dark); return <View style={[styles.pill, { backgroundColor: tone === 'accent' ? C.accent : C.line }]}><Text style={[styles.pillText, { color: tone === 'accent' ? C.accentText : C.subtext }]}>{children}</Text></View>; }
export const styles = StyleSheet.create({ screen: { flex: 1 }, scroll: { flex: 1 }, footer: { marginTop: 'auto', alignItems: 'center', paddingTop: 30, paddingHorizontal: 20 }, footerBrand: { fontSize: 13, letterSpacing: 3, fontWeight: '700' }, footerTag: { fontSize: 11, marginTop: 5, opacity: 0.7 }, header: { paddingHorizontal: 20, paddingTop: 6, paddingBottom: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 }, title: { fontSize: 26, fontWeight: '700' }, subtitle: { fontSize: 14, marginTop: 6 }, card: { marginHorizontal: 20, borderRadius: 10, borderWidth: 1, padding: 17, marginBottom: 14 }, label: { fontSize: 12, fontFamily: fonts.medium }, metric: { flex: 1 }, metricValue: { fontSize: 25, fontWeight: '700', marginTop: 6 }, metricUnit: { fontSize: 12, fontWeight: '500' }, row: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: 1, paddingVertical: 8 }, rowLabel: { fontSize: 13, flex: 1 }, rowValue: { fontSize: 13, maxWidth: '52%', textAlign: 'right' }, pill: { borderRadius: 20, paddingHorizontal: 10, paddingVertical: 5, alignSelf: 'flex-start' }, pillText: { fontSize: 11, fontFamily: fonts.medium }, });
